const env = process.env

const config = {
  AWS_ID: env.LA_AWS_ID,
  AWS_KEY: env.LA_AWS_KEY,
  AWS_REGION: env.LA_AWS_REGION || 'us-east-1',
  S3_BUCKET_PAGE: env.LA_S3_BUCKET_PAGE,
  PAGE_TABLE: env.LA_PAGE_TABLE,
  COLLECTION_TABLE: env.LA_COLLECTION_TABLE,
  COLLECTION_ITEM_TABLE: env.LA_COLLECTION_ITEM_TABLE,
  LISTS_TABLE: env.LA_LISTS_TABLE,
  LIST_SUBSCRIBERS_TABLE: env.LA_LIST_SUBSCRIBERS_TABLE,
  CF_KEY: env.LA_CF_KEY,
  CF_EMAIL: env.LA_CF_EMAIL,
  CF_ZONEID: env.LA_CF_ZONEID,
  IMGUR_ID: env.LA_IMGUR_ID,
  IMGUR_SECRET: env.LA_IMGUR_SECRET,
  API_URL: env.LA_API_URL,
  S3_BUCKET_LIST: env.LA_S3_BUCKET_LIST,
  DOMAIN: env.LA_DOMAIN,
  PORT: env.PORT || 3000

}

export {
  config
}
